 author       = "Patty (Design and funding) & Tally (Code)";                    // Affects Arma 3 Launcher, when the mod are loaded as local
 name         = "Patty's Special Abilities";                                   // Name of your mod
 tooltip      = "Patty's Special Abilities";                                  // Shown when Mouse hovers over mod-icon
 tooltipOwned = "Patty's Special Abilities";                                 // Tool tip displayed when the mouse is left over, in the main menu
 actionName   = "";                                                         // Button-text
 action       = "";                                                        // Website URL, that can be accessed from the expansions menu
 overview     = "A set of abilities compatible with patty's role-system"; // Supports structured text
 hideName     = 0;                                                       // Hide the extension name
 hidePicture  = 0;                                                      // Hide the extension menu
 dlcColor[]   = {0.8,0.8,0.3,1};                                       // Color used for DLC stripes and backgrounds (RGBA)
 picture      = "[P] Yellow.paa";                                     // Picture displayed from the expansions menu. Optimal size is 2048x1024
 logoSmall    = "[P] Yellow.paa";                                    // Display in creative lists, next to the entities added by the mod
 logo         = "[P] Yellow.paa";                                   // Logo displayed in the main menu
 logoOver     = "[P] Yellow.paa";                                  // When the mouse is over, in the main menu