 author       = "Dom, Patty & Tally";                      // Affects Arma 3 Launcher, when the mod are loaded as local
 name         = "Patty's Rolesystem";                     // Name of your mod
 tooltip      = "Patty's Rolesystem";                    // Shown when Mouse hovers over mod-icon
 tooltipOwned = "Patty's Rolesystem";                   // Tool tip displayed when the mouse is left over, in the main menu
 actionName   = "";                                    // Button-text
 action       = "";                                   // Website URL, that can be accessed from the expansions menu
 overview     = "A modified version of Doms role system"; // Supports structured text
 hideName     = 0;                                  // Hide the extension name
 hidePicture  = 0;                                 // Hide the extension menu
 dlcColor[]   = {0.23,0.39,0.30,1};               // Color used for DLC stripes and backgrounds (RGBA)
 picture      = "[P] red.paa";                   // Picture displayed from the expansions menu. Optimal size is 2048x1024
 logoSmall    = "[P] red.paa";                  // Display in creative lists, next to the entities added by the mod
 logo         = "[P] red.paa";                 // Logo displayed in the main menu
 logoOver     = "[P] red.paa";                // When the mouse is over, in the main menu