 author       = "Tally & Dom";                             // Affects Arma 3 Launcher, when the mod are loaded as local
 name         = "Patty's Mod";                            // Name of your mod
 tooltip      = "Patty's Mod";                           // Shown when Mouse hovers over mod-icon
 tooltipOwned = "Patty's Mod";                          // Tool tip displayed when the mouse is left over, in the main menu
 actionName   = "";                                    // Button-text
 action       = "";                                   // Website URL, that can be accessed from the expansions menu
 overview     = "Div features for Patty's gamemode"; // Supports structured text
 hideName     = 0;                                  // Hide the extension name
 hidePicture  = 0;                                 // Hide the extension menu
 dlcColor[]   = {0.23,0.39,0.30,1};               // Color used for DLC stripes and backgrounds (RGBA)
 picture      = "[P].paa";                       // Picture displayed from the expansions menu. Optimal size is 2048x1024
 logoSmall    = "[P].paa";                      // Display in creative lists, next to the entities added by the mod
 logo         = "[P].paa";                     // Logo displayed in the main menu
 logoOver     = "[P].paa";                    // When the mouse is over, in the main menu